### ISSUE TITLE
Duplicate Noto Tifininagh fonts for script variants in the main ZIP package containing all fonts

### ISSUE THREAD

**Issue by verdy-p** [notofonts/tifinagh#9]
The current "main" package containing all Noto (also Cousine, Arimo and Tinos) fonts is duplicating "Noto Tifinagh" fonts for script variants with suffixes (Adrar, AgrawImazighen, Ahaggar, Air, APT, Azawagh, Ghat, Hawad, RhissakaIxa, SIL, and Tawellemmet):
![image](https://user-images.githubusercontent.com/1387035/143627755-89d1ab5d-e24d-4020-a65e-d90053e6ebe1.png)
This occurs in the collections for the following formats: hinted/ttf, unhinted/otf, unhinted/ttf; but not in the "archive" pack

Also reported in https://github.com/google/fonts/issues/4110

**Comment by simoncozens** [comment]
The original problem is the same as issue #10.

The question of why we need style-specific fonts in the first place is a different one. I don't know the reason for the different variants but by guess is that they are not technically *language* specific variations but orthographic variations in different regions. (At least that's what the Unicode Standard appears to suggest) So I'm not sure it would be correct to use OpenType script/language codes to distinguish between them; even if we could, selection of font features by language tags in browsers is generally reasonable but in design applications can often be very hit-and-miss.

Similarly, it would of course be lovely to have it all encoded separately in Unicode and be able to build everything into a single font (the current multiple export process and the feature code to support it is fiendishly complex), but requiring everyone to add variant selectors to every single character that has regional variants just because a user wants the text to be displayed in their own variant is also not a great solution and pushes a lot of the cost of localization onto the user.

**Comment by simoncozens** [comment]
The distribution is now fixed; there's only one NotoSansTifinagh directory.

**Comment by verdy-p** [comment]
> The original problem is the same as issue #10.
> 
> The question of why we need style-specific fonts in the first place is a different one. I don't know the reason for the different variants but by guess is that they are not technically _language_ specific variations but orthographic variations in different regions. (At least that's what the Unicode Standard appears to suggest) So I'm not sure it would be correct to use OpenType script/language codes to distinguish between them; even if we could, selection of font features by language tags in browsers is generally reasonable but in design applications can often be very hit-and-miss.

But OpenType includes the support for language-specific variants (with "locl" feature, internally indexed by locale codes). This is also described in various OpenType documents for specific scripts (see for example the "mym2" script feature set for Myanmar). This means that a single font can support language-specific variations. Making the fonits even easier to use (provided that the renderer is instructed with the language to use, from the document, e.g. with BCP47 codes iin `lang=""` attributes of HTML; note that OpenType however does not use directly BCP47 locale tags, but has defined its own collection of codes (with fixed sizes) for languages or orthographic variants: it's up to the renderer to map the applications' locale codes to OpenType codes, using the specification of OpenType; applications may use also their own locale codes, not necessarily BCP47 but for example Windows LCID; this does not matter much here how this mapping is performed)

**Comment by moyogo** [comment]
> But OpenType includes the support for language-specific variants (with "locl" feature, internally indexed by locale codes). [...] This means that a single font can support language-specific variations.

There is no 1-to-1 mapping between the different Tifinagh styles and BCP47 nor OpenType Language Systems tags. For example the SIL and APT styles overlap in Niger.

> Making the fonits even easier to use [...].

The "locl" feature support is pretty limited and is not easy to use in all applications.
Separate fonts is the easiest solution that works everywhere for everyone.
